version: '3.8'

services:
  # Your FastAPI Backend
  benyon-backend:
    build: .
    container_name: benyon-backend
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM_NAME=team_online
      - KEYCLOAK_BACKEND_CLIENT_ID=benyon_be
      - KEYCLOAK_BACKEND_CLIENT_SECRET=KpS08hhGvpAII7Z3CbXZC4QiXCmQfInL
    volumes:
      - ./data/remote:/app/data/remote
      - ./data/backup:/app/data/backup
      - ./data/preview:/app/data/preview
    depends_on:
      - keycloak
    networks:
      - benyon-network
    restart: unless-stopped

  # Keycloak Authentication Server
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin123
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak123
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command:
      - start-dev
    networks:
      - benyon-network
    restart: unless-stopped

  # PostgreSQL Database for Keycloak
  postgres:
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - benyon-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - benyon-backend
      - keycloak
    networks:
      - benyon-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  benyon-network:
    driver: bridge