version: '3.8'

services:
  # Your FastAPI Backend
  benyon-backend:
    build: .
    container_name: benyon-backend
    ports:
      - "8000:8000"
    env_file:
      - secrets.env
    environment:
      - KEYCLOAK_URL=http://96.30.199.117:8080
      - KEYCLOAK_REALM_NAME=team_online
      - KEYCLOAK_BACKEND_CLIENT_ID=benyon_be
    volumes:
      - ./data/remote:/app/data/remote
      - ./data/backup:/app/data/backup
      - ./data/preview:/app/data/preview
    networks:
      - beynon-network
    restart: unless-stopped

networks:
  beynon-network:
    driver: bridge